<?php

namespace App\Console\Commands;

use App\Models\RouteMetadata;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Scan Routes Command
 *
 * Scans the sidebar navigation and populates the route_metadata table
 * with hierarchical descriptions for global search functionality.
 */
class ScanRoutesCommand extends Command
{
    protected $signature = 'routes:scan {--fresh : Clear existing metadata before scanning}';
    protected $description = 'Scan sidebar navigation and populate route metadata for search';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('Scanning routes from sidebar navigation...');

        if ($this->option('fresh')) {
            RouteMetadata::truncate();
            $this->warn('Cleared existing route metadata.');
        }

        $routes = $this->getRouteDefinitions();

        $bar = $this->output->createProgressBar(count($routes));
        $bar->start();

        $created = 0;
        $updated = 0;

        foreach ($routes as $route) {
            $existing = RouteMetadata::where('route_name', $route['route_name'])->first();

            if ($existing) {
                $existing->update($route);
                $updated++;
            } else {
                RouteMetadata::create($route);
                $created++;
            }

            $bar->advance();
        }

        $bar->finish();
        $this->newLine(2);
        $this->info("Route scan complete: {$created} created, {$updated} updated.");

        return Command::SUCCESS;
    }

    /**
     * Get all route definitions with hierarchy metadata
     */
    protected function getRouteDefinitions(): array
    {
        return [
            // ========================================
            // GLOBAL SECTION (All Roles)
            // ========================================
            [
                'route_name' => 'home',
                'url' => '/home',
                'title' => 'Dashboard',
                'description' => 'Main dashboard showing overview statistics, quick actions, and system notifications. Your central hub for accessing all modules.',
                'section' => 'Global',
                'parent_section' => null,
                'icon' => 'mdi-view-dashboard-outline',
                'keywords' => ['dashboard', 'home', 'overview', 'statistics', 'main', 'start'],
                'roles' => [],
                'permissions' => [],
                'hierarchy_path' => 'Dashboard',
                'sort_order' => 1,
            ],
            [
                'route_name' => 'hr.ess.my-profile',
                'url' => '/hr/ess/my-profile',
                'title' => 'My Profile',
                'description' => 'View and manage your personal profile information, contact details, and account settings.',
                'section' => 'Global',
                'parent_section' => null,
                'icon' => 'mdi-account-circle',
                'keywords' => ['profile', 'my profile', 'personal', 'account', 'settings', 'user'],
                'roles' => [],
                'permissions' => [],
                'hierarchy_path' => 'My Profile',
                'sort_order' => 2,
            ],
            [
                'route_name' => 'chat.index',
                'url' => '/chat',
                'title' => 'Messenger',
                'description' => 'Internal messaging system for communicating with colleagues. Send and receive messages, create group chats.',
                'section' => 'Global',
                'parent_section' => null,
                'icon' => 'mdi-message-text-outline',
                'keywords' => ['messenger', 'chat', 'messages', 'communication', 'inbox', 'conversation'],
                'roles' => [],
                'permissions' => [],
                'hierarchy_path' => 'Messenger',
                'sort_order' => 3,
            ],
            [
                'route_name' => 'inventory.requisitions.index',
                'url' => '/inventory/requisitions',
                'title' => 'Requisitions',
                'description' => 'Request items from the store. View your requisition history and track request status.',
                'section' => 'Global',
                'parent_section' => null,
                'icon' => 'mdi-swap-horizontal',
                'keywords' => ['requisitions', 'request', 'items', 'store', 'supplies', 'order'],
                'roles' => [],
                'permissions' => [],
                'hierarchy_path' => 'Requisitions',
                'sort_order' => 4,
            ],

            // ========================================
            // EMPLOYEE SELF-SERVICE (ESS)
            // ========================================
            [
                'route_name' => 'hr.ess.index',
                'url' => '/hr/ess',
                'title' => 'ESS Dashboard',
                'description' => 'Employee Self-Service dashboard. Access your HR information, leave requests, payslips, and more.',
                'section' => 'My HR Portal',
                'parent_section' => null,
                'icon' => 'mdi-account-circle-outline',
                'keywords' => ['ess', 'employee', 'self service', 'hr portal', 'my hr'],
                'roles' => [],
                'permissions' => ['ess.access'],
                'hierarchy_path' => 'My HR Portal > ESS Dashboard',
                'sort_order' => 10,
            ],
            [
                'route_name' => 'hr.ess.my-leave',
                'url' => '/hr/ess/my-leave',
                'title' => 'My Leave',
                'description' => 'View your leave balance, request new leave, and track leave request status.',
                'section' => 'My HR Portal',
                'parent_section' => null,
                'icon' => 'mdi-calendar-check',
                'keywords' => ['leave', 'vacation', 'time off', 'annual leave', 'sick leave', 'absence'],
                'roles' => [],
                'permissions' => ['ess.access'],
                'hierarchy_path' => 'My HR Portal > My Leave',
                'sort_order' => 11,
            ],
            [
                'route_name' => 'hr.ess.my-payslips',
                'url' => '/hr/ess/my-payslips',
                'title' => 'My Payslips',
                'description' => 'View and download your monthly payslips. Access salary history and payment details.',
                'section' => 'My HR Portal',
                'parent_section' => null,
                'icon' => 'mdi-file-document-outline',
                'keywords' => ['payslip', 'salary', 'pay', 'wages', 'earnings', 'payment', 'slip'],
                'roles' => [],
                'permissions' => ['ess.view-payslips'],
                'hierarchy_path' => 'My HR Portal > My Payslips',
                'sort_order' => 12,
            ],
            [
                'route_name' => 'hr.ess.my-disciplinary',
                'url' => '/hr/ess/my-disciplinary',
                'title' => 'My Disciplinary',
                'description' => 'View disciplinary records and queries issued to you.',
                'section' => 'My HR Portal',
                'parent_section' => null,
                'icon' => 'mdi-alert-circle-outline',
                'keywords' => ['disciplinary', 'query', 'warning', 'misconduct'],
                'roles' => [],
                'permissions' => ['ess.access'],
                'hierarchy_path' => 'My HR Portal > My Disciplinary',
                'sort_order' => 13,
            ],

            // ========================================
            // HEALTH RECORDS / RECEPTIONIST SECTION
            // ========================================
            [
                'route_name' => 'reception.workbench',
                'url' => '/reception/workbench',
                'title' => 'Health Records Workbench',
                'description' => 'Central workbench for health records management. Register patients, manage encounters, queue management, and appointments.',
                'section' => 'Health Records',
                'parent_section' => null,
                'icon' => 'mdi-desktop-mac-dashboard',
                'keywords' => ['reception', 'workbench', 'health records', 'front desk', 'registration', 'queue'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'RECEPTIONIST'],
                'permissions' => [],
                'hierarchy_path' => 'Health Records > Workbench',
                'sort_order' => 20,
            ],
            [
                'route_name' => 'patient.create',
                'url' => '/patient/create',
                'title' => 'New Patient Registration',
                'description' => 'Register a new patient. Capture demographics, contact information, next of kin, and insurance details.',
                'section' => 'Health Records',
                'parent_section' => 'Patients',
                'icon' => 'mdi-account-plus',
                'keywords' => ['patient', 'registration', 'new patient', 'register', 'create', 'admission'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'RECEPTIONIST', 'BILLER'],
                'permissions' => [],
                'hierarchy_path' => 'Health Records > Patients > New Registration',
                'sort_order' => 21,
            ],
            [
                'route_name' => 'patient.index',
                'url' => '/patient',
                'title' => 'All Patients',
                'description' => 'View and search all registered patients. Access patient records, history, and manage patient information.',
                'section' => 'Health Records',
                'parent_section' => 'Patients',
                'icon' => 'mdi-account-multiple-outline',
                'keywords' => ['patients', 'all patients', 'patient list', 'search patient', 'find patient'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'RECEPTIONIST', 'BILLER', 'NURSE', 'DOCTOR', 'PHARMACIST', 'LAB SCIENTIST'],
                'permissions' => [],
                'hierarchy_path' => 'Health Records > Patients > All Patients',
                'sort_order' => 22,
            ],

            // ========================================
            // BILLING SECTION
            // ========================================
            [
                'route_name' => 'billing.workbench',
                'url' => '/billing/workbench',
                'title' => 'Billing Workbench',
                'description' => 'Central billing workbench. Process payments, generate invoices, manage patient accounts, and handle refunds.',
                'section' => 'Billing',
                'parent_section' => null,
                'icon' => 'mdi-cash-register',
                'keywords' => ['billing', 'workbench', 'payments', 'cashier', 'invoice', 'receipt', 'pay'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS', 'BILLER', 'RECEPTIONIST'],
                'permissions' => [],
                'hierarchy_path' => 'Billing > Workbench',
                'sort_order' => 30,
            ],
            [
                'route_name' => 'product-or-service-request.index',
                'url' => '/product-or-service-request',
                'title' => 'All Payment Requests',
                'description' => 'View all pending and completed payment requests. Products and services awaiting payment.',
                'section' => 'Billing',
                'parent_section' => 'Accounts',
                'icon' => 'mdi-cash-multiple',
                'keywords' => ['payment', 'requests', 'pending', 'bills', 'charges', 'services'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS', 'BILLER', 'RECEPTIONIST'],
                'permissions' => [],
                'hierarchy_path' => 'Billing > Accounts > All Payment Requests',
                'sort_order' => 31,
            ],
            [
                'route_name' => 'my-transactions',
                'url' => '/my-transactions',
                'title' => 'My Transactions',
                'description' => 'View all transactions processed by you. Payment history and daily transaction summary.',
                'section' => 'Billing',
                'parent_section' => 'Accounts',
                'icon' => 'mdi-history',
                'keywords' => ['transactions', 'my transactions', 'history', 'payments made', 'cashier log'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS', 'BILLER', 'RECEPTIONIST'],
                'permissions' => [],
                'hierarchy_path' => 'Billing > Accounts > My Transactions',
                'sort_order' => 32,
            ],
            [
                'route_name' => 'allPrevEncounters',
                'url' => '/all-previous-encounters',
                'title' => 'All Previous Consultations',
                'description' => 'View historical patient consultations and encounters across all departments.',
                'section' => 'Billing',
                'parent_section' => 'Consultations',
                'icon' => 'mdi-stethoscope',
                'keywords' => ['consultations', 'encounters', 'history', 'previous', 'visits'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS', 'BILLER', 'RECEPTIONIST'],
                'permissions' => [],
                'hierarchy_path' => 'Health Records > Consultations > All Previous',
                'sort_order' => 33,
            ],

            // ========================================
            // PHARMACY SECTION
            // ========================================
            [
                'route_name' => 'pharmacy.workbench',
                'url' => '/pharmacy/workbench',
                'title' => 'Pharmacy Workbench',
                'description' => 'Central pharmacy workbench. Dispense medications, view prescriptions, manage drug inventory.',
                'section' => 'Pharmacy',
                'parent_section' => null,
                'icon' => 'mdi-pill',
                'keywords' => ['pharmacy', 'workbench', 'dispense', 'drugs', 'medications', 'prescriptions'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'PHARMACIST'],
                'permissions' => [],
                'hierarchy_path' => 'Pharmacy > Workbench',
                'sort_order' => 40,
            ],
            [
                'route_name' => 'product-category.index',
                'url' => '/product-category',
                'title' => 'Product Categories',
                'description' => 'Manage product categories for pharmacy and store items. Organize drugs and supplies.',
                'section' => 'Pharmacy',
                'parent_section' => 'Product Management',
                'icon' => 'mdi-folder-outline',
                'keywords' => ['categories', 'product categories', 'drug categories', 'organize'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'PHARMACIST', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Pharmacy > Product Management > Categories',
                'sort_order' => 41,
            ],
            [
                'route_name' => 'stores.index',
                'url' => '/stores',
                'title' => 'Stores',
                'description' => 'Manage store locations. Create and configure pharmacy and inventory stores.',
                'section' => 'Pharmacy',
                'parent_section' => 'Product Management',
                'icon' => 'mdi-store',
                'keywords' => ['stores', 'locations', 'pharmacy store', 'warehouse', 'depot'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'PHARMACIST', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Pharmacy > Product Management > Stores',
                'sort_order' => 42,
            ],
            [
                'route_name' => 'products.index',
                'url' => '/products',
                'title' => 'Products',
                'description' => 'Manage products and medications. Add, edit, and view drug information, pricing, and stock levels.',
                'section' => 'Pharmacy',
                'parent_section' => 'Product Management',
                'icon' => 'mdi-package-variant',
                'keywords' => ['products', 'drugs', 'medications', 'items', 'inventory', 'stock'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'PHARMACIST', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Pharmacy > Product Management > Products',
                'sort_order' => 43,
            ],

            // ========================================
            // STORE / INVENTORY SECTION
            // ========================================
            [
                'route_name' => 'inventory.store-workbench.index',
                'url' => '/inventory/store-workbench',
                'title' => 'Store Workbench',
                'description' => 'Central store management workbench. Handle requisitions, stock management, and inventory operations.',
                'section' => 'Store / Inventory',
                'parent_section' => null,
                'icon' => 'mdi-store',
                'keywords' => ['store', 'workbench', 'inventory', 'stock', 'warehouse'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Store / Inventory > Workbench',
                'sort_order' => 50,
            ],
            [
                'route_name' => 'services-category.index',
                'url' => '/services-category',
                'title' => 'Service Categories',
                'description' => 'Manage service categories for lab tests, procedures, and other clinical services.',
                'section' => 'Store / Inventory',
                'parent_section' => 'Services Management',
                'icon' => 'mdi-folder-cog',
                'keywords' => ['service categories', 'test categories', 'procedure types'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Store / Inventory > Services Management > Categories',
                'sort_order' => 51,
            ],
            [
                'route_name' => 'services.index',
                'url' => '/services',
                'title' => 'Medical Lab Services',
                'description' => 'Manage laboratory test services. Configure test names, prices, and parameters.',
                'section' => 'Store / Inventory',
                'parent_section' => 'Services Management',
                'icon' => 'mdi-test-tube',
                'keywords' => ['lab services', 'tests', 'investigations', 'medical lab'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Store / Inventory > Services Management > Med Lab Services',
                'sort_order' => 52,
            ],
            [
                'route_name' => 'procedure-categories.index',
                'url' => '/procedure-categories',
                'title' => 'Procedure Categories',
                'description' => 'Manage medical procedure categories. Organize surgical and clinical procedures.',
                'section' => 'Store / Inventory',
                'parent_section' => 'Services Management',
                'icon' => 'mdi-medical-bag',
                'keywords' => ['procedure categories', 'surgery types', 'clinical procedures'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Store / Inventory > Services Management > Procedure Categories',
                'sort_order' => 53,
            ],
            [
                'route_name' => 'inventory.purchase-orders.index',
                'url' => '/inventory/purchase-orders',
                'title' => 'Purchase Orders',
                'description' => 'Create and manage purchase orders. Order supplies from suppliers and track deliveries.',
                'section' => 'Store / Inventory',
                'parent_section' => 'Inventory Operations',
                'icon' => 'mdi-cart-arrow-down',
                'keywords' => ['purchase orders', 'PO', 'ordering', 'suppliers', 'procurement'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'STORE', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Store / Inventory > Inventory Operations > Purchase Orders',
                'sort_order' => 54,
            ],
            [
                'route_name' => 'inventory.expenses.index',
                'url' => '/inventory/expenses',
                'title' => 'Expenses',
                'description' => 'Record and manage store expenses. Track operational costs and supplier payments.',
                'section' => 'Store / Inventory',
                'parent_section' => 'Inventory Operations',
                'icon' => 'mdi-cash-minus',
                'keywords' => ['expenses', 'costs', 'payments', 'expenditure', 'spending'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'STORE', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Store / Inventory > Inventory Operations > Expenses',
                'sort_order' => 55,
            ],

            // ========================================
            // NURSING SECTION
            // ========================================
            [
                'route_name' => 'nursing-workbench.index',
                'url' => '/nursing-workbench',
                'title' => 'Nursing Workbench',
                'description' => 'Central nursing workbench. Record vitals, manage patient care, medication administration, and nursing notes.',
                'section' => 'Nursing',
                'parent_section' => null,
                'icon' => 'mdi-heart-pulse',
                'keywords' => ['nursing', 'workbench', 'vitals', 'patient care', 'ward', 'nurses'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'NURSE'],
                'permissions' => [],
                'hierarchy_path' => 'Nursing > Workbench',
                'sort_order' => 60,
            ],
            [
                'route_name' => 'admission-requests.index',
                'url' => '/admission-requests',
                'title' => 'Bed Requests',
                'description' => 'Manage patient admission and bed allocation requests. View pending admissions.',
                'section' => 'Nursing',
                'parent_section' => 'Admissions',
                'icon' => 'mdi-bed',
                'keywords' => ['bed requests', 'admissions', 'inpatient', 'ward', 'allocation'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'NURSE', 'RECEPTIONIST'],
                'permissions' => [],
                'hierarchy_path' => 'Nursing > Admissions > Bed Requests',
                'sort_order' => 61,
            ],
            [
                'route_name' => 'beds.index',
                'url' => '/beds',
                'title' => 'Manage Beds',
                'description' => 'Manage hospital beds and wards. View bed occupancy and configure bed assignments.',
                'section' => 'Nursing',
                'parent_section' => 'Admissions',
                'icon' => 'mdi-bed-empty',
                'keywords' => ['beds', 'wards', 'occupancy', 'bed management', 'rooms'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'NURSE', 'RECEPTIONIST'],
                'permissions' => [],
                'hierarchy_path' => 'Nursing > Admissions > Manage Beds',
                'sort_order' => 62,
            ],

            // ========================================
            // LAB SCIENTIST SECTION
            // ========================================
            [
                'route_name' => 'lab.workbench',
                'url' => '/lab/workbench',
                'title' => 'Lab Workbench',
                'description' => 'Central laboratory workbench. Process lab requests, enter results, and manage test workflows.',
                'section' => 'Medical Laboratory',
                'parent_section' => null,
                'icon' => 'mdi-flask-outline',
                'keywords' => ['lab', 'laboratory', 'workbench', 'tests', 'results', 'samples'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'LAB SCIENTIST'],
                'permissions' => [],
                'hierarchy_path' => 'Medical Laboratory > Workbench',
                'sort_order' => 70,
            ],

            // ========================================
            // RADIOLOGY / IMAGING SECTION
            // ========================================
            [
                'route_name' => 'imaging.workbench',
                'url' => '/imaging/workbench',
                'title' => 'Imaging Workbench',
                'description' => 'Central imaging workbench. Process radiology requests, upload images, and enter reports.',
                'section' => 'Imaging / Radiology',
                'parent_section' => null,
                'icon' => 'mdi-radioactive',
                'keywords' => ['imaging', 'radiology', 'workbench', 'xray', 'scan', 'ultrasound', 'CT'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'RADIOLOGIST'],
                'permissions' => [],
                'hierarchy_path' => 'Imaging / Radiology > Workbench',
                'sort_order' => 80,
            ],

            // ========================================
            // DOCTOR SECTION
            // ========================================
            [
                'route_name' => 'doctor.workbench.index',
                'url' => '/doctor/workbench',
                'title' => 'Doctor Workbench',
                'description' => 'Central doctor workbench. View patient queue, conduct consultations, prescribe medications, and order tests.',
                'section' => 'Doctor',
                'parent_section' => null,
                'icon' => 'mdi-stethoscope',
                'keywords' => ['doctor', 'workbench', 'consultation', 'prescribe', 'diagnosis', 'treatment'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'DOCTOR'],
                'permissions' => [],
                'hierarchy_path' => 'Doctor > Workbench',
                'sort_order' => 90,
            ],

            // ========================================
            // HMO / INSURANCE SECTION
            // ========================================
            [
                'route_name' => 'hmo.workbench',
                'url' => '/hmo/workbench',
                'title' => 'HMO Workbench',
                'description' => 'HMO and insurance management workbench. Process claims, verify coverage, and manage HMO accounts.',
                'section' => 'HMO / Insurance',
                'parent_section' => null,
                'icon' => 'mdi-shield-check',
                'keywords' => ['hmo', 'insurance', 'claims', 'coverage', 'verification', 'NHIS'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HMO OFFICER'],
                'permissions' => [],
                'hierarchy_path' => 'HMO / Insurance > Workbench',
                'sort_order' => 100,
            ],
            [
                'route_name' => 'hmos.index',
                'url' => '/hmos',
                'title' => 'HMO List',
                'description' => 'Manage HMO providers. Add, edit, and configure insurance companies and their plans.',
                'section' => 'HMO / Insurance',
                'parent_section' => null,
                'icon' => 'mdi-hospital-building',
                'keywords' => ['hmo list', 'insurance providers', 'health plans'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HMO OFFICER'],
                'permissions' => [],
                'hierarchy_path' => 'HMO / Insurance > HMO List',
                'sort_order' => 101,
            ],

            // ========================================
            // ACCOUNTING SECTION
            // ========================================
            [
                'route_name' => 'accounting.dashboard',
                'url' => '/accounting',
                'title' => 'Accounting Dashboard',
                'description' => 'Financial overview dashboard. View revenue, expenses, and key financial metrics.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-calculator',
                'keywords' => ['accounting', 'dashboard', 'finance', 'financial', 'revenue', 'overview'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Dashboard',
                'sort_order' => 110,
            ],
            [
                'route_name' => 'accounting.journal-entries.index',
                'url' => '/accounting/journal-entries',
                'title' => 'Journal Entries',
                'description' => 'View and create journal entries. Record financial transactions and adjustments.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-book-open-page-variant',
                'keywords' => ['journal', 'entries', 'transactions', 'ledger', 'debit', 'credit'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Journal Entries',
                'sort_order' => 111,
            ],
            [
                'route_name' => 'accounting.chart-of-accounts.index',
                'url' => '/accounting/chart-of-accounts',
                'title' => 'Chart of Accounts',
                'description' => 'Manage chart of accounts. Configure asset, liability, equity, revenue, and expense accounts.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-file-tree',
                'keywords' => ['chart of accounts', 'COA', 'accounts', 'ledger accounts', 'GL'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Chart of Accounts',
                'sort_order' => 112,
            ],
            [
                'route_name' => 'accounting.reports.index',
                'url' => '/accounting/reports',
                'title' => 'Accounting Reports',
                'description' => 'Generate financial reports. Trial balance, income statement, balance sheet, and more.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-chart-bar',
                'keywords' => ['reports', 'financial reports', 'trial balance', 'income statement', 'balance sheet'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Reports',
                'sort_order' => 113,
            ],
            [
                'route_name' => 'accounting.credit-notes.index',
                'url' => '/accounting/credit-notes',
                'title' => 'Credit Notes',
                'description' => 'Manage credit notes and refunds. Process patient refunds and adjustments.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-file-document-outline',
                'keywords' => ['credit notes', 'refunds', 'adjustments', 'reversals'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Credit Notes',
                'sort_order' => 114,
            ],
            [
                'route_name' => 'accounting.periods',
                'url' => '/accounting/periods',
                'title' => 'Fiscal Periods',
                'description' => 'Manage accounting periods and fiscal years. Open, close, and configure financial periods.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-calendar-range',
                'keywords' => ['fiscal', 'periods', 'fiscal year', 'accounting period', 'year end'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Fiscal Periods',
                'sort_order' => 115,
            ],
            [
                'route_name' => 'inventory.purchase-orders.accounts-payable',
                'url' => '/inventory/purchase-orders/accounts-payable',
                'title' => 'Accounts Payable',
                'description' => 'View and manage accounts payable. Track supplier invoices and outstanding payments.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-currency-ngn',
                'keywords' => ['accounts payable', 'AP', 'supplier payments', 'outstanding', 'creditors'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Accounts Payable',
                'sort_order' => 116,
            ],
            [
                'route_name' => 'banks.index',
                'url' => '/banks',
                'title' => 'Banks',
                'description' => 'Manage bank accounts. Configure payment accounts and bank details.',
                'section' => 'Accounting',
                'parent_section' => null,
                'icon' => 'mdi-bank',
                'keywords' => ['banks', 'bank accounts', 'payment methods', 'financial institutions'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'ACCOUNTS'],
                'permissions' => [],
                'hierarchy_path' => 'Accounting > Banks',
                'sort_order' => 117,
            ],

            // ========================================
            // HUMAN RESOURCES SECTION
            // ========================================
            [
                'route_name' => 'hr.workbench.index',
                'url' => '/hr/workbench',
                'title' => 'HR Workbench',
                'description' => 'Central HR management workbench. Manage staff, payroll, leave, and disciplinary matters.',
                'section' => 'Human Resources',
                'parent_section' => null,
                'icon' => 'mdi-account-group',
                'keywords' => ['hr', 'human resources', 'workbench', 'staff', 'employees', 'personnel'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['hr-workbench.access'],
                'hierarchy_path' => 'Human Resources > Workbench',
                'sort_order' => 120,
            ],
            [
                'route_name' => 'hr.leave-calendar.index',
                'url' => '/hr/leave-calendar',
                'title' => 'Leave Calendar',
                'description' => 'Visual calendar showing all staff leave. Plan coverage and view absence patterns.',
                'section' => 'Human Resources',
                'parent_section' => 'Leave Management',
                'icon' => 'mdi-calendar-month',
                'keywords' => ['leave calendar', 'absence calendar', 'staff leave', 'vacation planner'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['leave-request.view'],
                'hierarchy_path' => 'Human Resources > Leave Management > Calendar',
                'sort_order' => 121,
            ],
            [
                'route_name' => 'hr.leave-types.index',
                'url' => '/hr/leave-types',
                'title' => 'Leave Types',
                'description' => 'Configure leave types. Annual leave, sick leave, maternity, and custom leave categories.',
                'section' => 'Human Resources',
                'parent_section' => 'Leave Management',
                'icon' => 'mdi-format-list-bulleted-type',
                'keywords' => ['leave types', 'annual leave', 'sick leave', 'maternity', 'leave categories'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['leave-type.view'],
                'hierarchy_path' => 'Human Resources > Leave Management > Types',
                'sort_order' => 122,
            ],
            [
                'route_name' => 'hr.leave-requests.index',
                'url' => '/hr/leave-requests',
                'title' => 'Leave Requests',
                'description' => 'View and process staff leave requests. Approve, reject, and manage leave applications.',
                'section' => 'Human Resources',
                'parent_section' => 'Leave Management',
                'icon' => 'mdi-calendar-check',
                'keywords' => ['leave requests', 'leave applications', 'approve leave', 'time off requests'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['leave-request.view'],
                'hierarchy_path' => 'Human Resources > Leave Management > Requests',
                'sort_order' => 123,
            ],
            [
                'route_name' => 'hr.leave-balances.index',
                'url' => '/hr/leave-balances',
                'title' => 'Leave Balances',
                'description' => 'View and adjust staff leave balances. Track remaining leave days for all employees.',
                'section' => 'Human Resources',
                'parent_section' => 'Leave Management',
                'icon' => 'mdi-scale-balance',
                'keywords' => ['leave balances', 'remaining leave', 'leave days', 'entitlement'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['leave-balance.view'],
                'hierarchy_path' => 'Human Resources > Leave Management > Balances',
                'sort_order' => 124,
            ],
            [
                'route_name' => 'hr.disciplinary.index',
                'url' => '/hr/disciplinary',
                'title' => 'Disciplinary Queries',
                'description' => 'Manage staff disciplinary issues. Issue queries, warnings, and track disciplinary actions.',
                'section' => 'Human Resources',
                'parent_section' => 'Disciplinary',
                'icon' => 'mdi-alert-circle',
                'keywords' => ['disciplinary', 'queries', 'warnings', 'misconduct', 'staff issues'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['disciplinary.view'],
                'hierarchy_path' => 'Human Resources > Disciplinary > Queries',
                'sort_order' => 125,
            ],
            [
                'route_name' => 'hr.suspensions.index',
                'url' => '/hr/suspensions',
                'title' => 'Suspensions',
                'description' => 'Manage staff suspensions. Record and track employee suspension periods.',
                'section' => 'Human Resources',
                'parent_section' => 'Disciplinary',
                'icon' => 'mdi-account-off',
                'keywords' => ['suspensions', 'suspended staff', 'disciplinary suspension'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['suspension.view'],
                'hierarchy_path' => 'Human Resources > Disciplinary > Suspensions',
                'sort_order' => 126,
            ],
            [
                'route_name' => 'hr.terminations.index',
                'url' => '/hr/terminations',
                'title' => 'Terminations',
                'description' => 'Manage employment terminations. Process resignations, dismissals, and retirements.',
                'section' => 'Human Resources',
                'parent_section' => 'Disciplinary',
                'icon' => 'mdi-account-remove',
                'keywords' => ['terminations', 'resignations', 'dismissals', 'exit', 'off-boarding'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['termination.view'],
                'hierarchy_path' => 'Human Resources > Disciplinary > Terminations',
                'sort_order' => 127,
            ],
            [
                'route_name' => 'hr.pay-heads.index',
                'url' => '/hr/pay-heads',
                'title' => 'Pay Heads',
                'description' => 'Configure payroll pay heads. Earnings, deductions, allowances, and other salary components.',
                'section' => 'Human Resources',
                'parent_section' => 'Payroll',
                'icon' => 'mdi-cash',
                'keywords' => ['pay heads', 'salary components', 'earnings', 'deductions', 'allowances'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['pay-head.view'],
                'hierarchy_path' => 'Human Resources > Payroll > Pay Heads',
                'sort_order' => 128,
            ],
            [
                'route_name' => 'hr.salary-profiles.index',
                'url' => '/hr/salary-profiles',
                'title' => 'Salary Profiles',
                'description' => 'Manage staff salary profiles. Configure individual salary structures and components.',
                'section' => 'Human Resources',
                'parent_section' => 'Payroll',
                'icon' => 'mdi-account-cash',
                'keywords' => ['salary profiles', 'salary structure', 'remuneration', 'compensation'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['salary-profile.view'],
                'hierarchy_path' => 'Human Resources > Payroll > Salary Profiles',
                'sort_order' => 129,
            ],
            [
                'route_name' => 'hr.payroll.index',
                'url' => '/hr/payroll',
                'title' => 'Payroll Batches',
                'description' => 'Process monthly payroll. Generate payslips, approve payments, and manage salary disbursement.',
                'section' => 'Human Resources',
                'parent_section' => 'Payroll',
                'icon' => 'mdi-cash-multiple',
                'keywords' => ['payroll', 'salary processing', 'payslips', 'monthly pay', 'wages'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => ['payroll-batch.view'],
                'hierarchy_path' => 'Human Resources > Payroll > Batches',
                'sort_order' => 130,
            ],

            // ========================================
            // ADMINISTRATION SECTION
            // ========================================
            [
                'route_name' => 'users.index',
                'url' => '/users',
                'title' => 'User Management',
                'description' => 'Manage system users. Create accounts, assign roles, and configure access permissions.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-account-cog',
                'keywords' => ['users', 'user management', 'accounts', 'access', 'login', 'credentials'],
                'roles' => ['SUPERADMIN', 'ADMIN'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > User Management',
                'sort_order' => 140,
            ],
            [
                'route_name' => 'staff.index',
                'url' => '/staff',
                'title' => 'Staff Management',
                'description' => 'Manage hospital staff records. Employee information, departments, and designations.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-account-group',
                'keywords' => ['staff', 'employees', 'personnel', 'workforce', 'team members'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'HR MANAGER'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > Staff Management',
                'sort_order' => 141,
            ],
            [
                'route_name' => 'roles.index',
                'url' => '/roles',
                'title' => 'Roles & Permissions',
                'description' => 'Configure user roles and permissions. Define access levels and security policies.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-shield-account',
                'keywords' => ['roles', 'permissions', 'access control', 'security', 'privileges'],
                'roles' => ['SUPERADMIN', 'ADMIN'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > Roles & Permissions',
                'sort_order' => 142,
            ],
            [
                'route_name' => 'departments.index',
                'url' => '/departments',
                'title' => 'Departments',
                'description' => 'Manage hospital departments. Configure organizational structure and department settings.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-domain',
                'keywords' => ['departments', 'units', 'sections', 'organizational structure'],
                'roles' => ['SUPERADMIN', 'ADMIN'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > Departments',
                'sort_order' => 143,
            ],
            [
                'route_name' => 'clinics.index',
                'url' => '/clinics',
                'title' => 'Clinics',
                'description' => 'Manage hospital clinics and consultation rooms. Configure clinic schedules and assignments.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-hospital-marker',
                'keywords' => ['clinics', 'consultation rooms', 'outpatient', 'clinic management'],
                'roles' => ['SUPERADMIN', 'ADMIN'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > Clinics',
                'sort_order' => 144,
            ],
            [
                'route_name' => 'wards.index',
                'url' => '/wards',
                'title' => 'Wards',
                'description' => 'Manage hospital wards. Configure inpatient units, bed capacity, and ward settings.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-bed-outline',
                'keywords' => ['wards', 'inpatient', 'units', 'bed management', 'ward configuration'],
                'roles' => ['SUPERADMIN', 'ADMIN'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > Wards',
                'sort_order' => 145,
            ],
            [
                'route_name' => 'suppliers.index',
                'url' => '/suppliers',
                'title' => 'Suppliers',
                'description' => 'Manage suppliers and vendors. Configure supplier information and payment terms.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-truck-delivery',
                'keywords' => ['suppliers', 'vendors', 'distributors', 'procurement'],
                'roles' => ['SUPERADMIN', 'ADMIN', 'STORE'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > Suppliers',
                'sort_order' => 146,
            ],
            [
                'route_name' => 'application-settings',
                'url' => '/application-settings',
                'title' => 'Application Settings',
                'description' => 'Configure system-wide application settings. Hospital information, branding, and preferences.',
                'section' => 'Administration',
                'parent_section' => null,
                'icon' => 'mdi-cog',
                'keywords' => ['settings', 'configuration', 'preferences', 'system settings', 'hospital settings'],
                'roles' => ['SUPERADMIN', 'ADMIN'],
                'permissions' => [],
                'hierarchy_path' => 'Administration > Application Settings',
                'sort_order' => 147,
            ],
        ];
    }
}
