@php
    $siteName = appsettings('site_name') ?? 'CoreHealth Hospital';
    $siteLogo = appsettings('site_logo');
    $hosAddress = appsettings('hos_address') ?? 'Healthcare Facility';
    $hosPhone = appsettings('hos_phone');
    $hosEmail = appsettings('hos_email');
    $hosColor = appsettings('hos_color') ?? '#011b33';
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store Physical Stock Verification Sheet - {{ $store->store_name }} - {{ date('d M Y') }}</title>
    <link rel="stylesheet" href="{{ asset('plugins/themify-icons/themify-icons.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/7.2.96/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="{{ asset('css/stock-verification-print.css') }}">
</head>
<body>

    {{-- Screen Action Bar --}}
    <div class="action-bar no-print">
        <div class="brand-label">
            <i class="mdi mdi-clipboard-check" style="font-size: 20px; color: #059669;"></i>
            <span>Store Physical Stock Verification &amp; Audit Sheet</span>
        </div>
        <div class="actions">
            <button class="btn-act" onclick="window.history.back()">
                <i class="mdi mdi-arrow-left"></i> Back to My Stock
            </button>
            <a href="{{ route('inventory.requisitions.my-stock.export-csv', request()->query()) }}" class="btn-act">
                <i class="mdi mdi-file-delimited-outline"></i> Export Audit CSV
            </a>
            <button class="btn-act btn-act-primary" onclick="window.print()">
                <i class="mdi mdi-printer"></i> Print Count Sheet (A4)
            </button>
        </div>
    </div>

    {{-- Printable Sheet Container --}}
    <div class="sheet">

        {{-- Verification Watermark Banner --}}
        <div class="verification-banner">
            <div class="banner-left">
                <i class="mdi mdi-shield-check" style="font-size: 16px;"></i>
                <span>Official Physical Inventory Verification &amp; Shelf Count Sheet</span>
            </div>
            <div class="banner-tag">MANDATORY STORE AUDIT</div>
        </div>

        {{-- Hospital Brand Header & Document Title --}}
        <div class="doc-header">
            <div class="hospital-brand">
                @if($siteLogo)
                    <img src="{{ asset('storage/' . $siteLogo) }}" alt="{{ $siteName }}" class="hospital-logo" onerror="this.style.display='none'">
                @endif
                <div>
                    <div class="hospital-name">{{ $siteName }}</div>
                    <div class="hospital-meta">
                        {{ $hosAddress }}
                        @if($hosPhone) &bull; Tel: {{ $hosPhone }} @endif
                        @if($hosEmail) &bull; Email: {{ $hosEmail }} @endif
                    </div>
                </div>
            </div>
            <div class="doc-title-box">
                <div class="audit-stamp-badge">
                    <i class="mdi mdi-check-decagram mr-1"></i> Physical Stock Audit
                </div>
                <div class="doc-title">Store Physical Stock Audit Sheet</div>
                <div class="doc-subtitle">Inventory Shelf Count &amp; Reconciliation Ledger</div>
            </div>
        </div>

        {{-- Metadata Strip --}}
        <div class="meta-strip">
            <div class="meta-item">
                <span class="label">Operating Store</span>
                <span class="value">{{ $store->store_name }} @if($store->code)({{ $store->code }})@endif</span>
            </div>
            <div class="meta-item">
                <span class="label">Store Role / Department</span>
                <span class="value">{{ ucwords(str_replace('_', ' ', $store->distribution_role)) }} &bull; {{ $store->ward->ward_name ?? $store->department->name ?? 'Global Unit' }}</span>
            </div>
            <div class="meta-item">
                <span class="label">Filter Applied</span>
                <span class="value">{{ $filterLabel }} @if($searchQuery) &bull; Q: "{{ $searchQuery }}" @endif</span>
            </div>
            <div class="meta-item">
                <span class="label">Generated By / Date</span>
                <span class="value">{{ $printedBy }} &bull; {{ $printDate }}</span>
            </div>
        </div>

        {{-- Summary KPIs --}}
        <div class="kpi-row">
            <div class="kpi-card">
                <div class="kpi-label">Stock Item Lines</div>
                <div class="kpi-val">{{ number_format($totalProducts) }}</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Total Recorded Units</div>
                <div class="kpi-val">{{ number_format($totalQuantity) }}</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Stock Valuation (Cost)</div>
                <div class="kpi-val">&#8358;{{ number_format($totalValuation, 2) }}</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Audit Verification State</div>
                <div class="kpi-val" style="font-size: 13px; color: #b45309;">Ready for Count</div>
            </div>
        </div>

        {{-- Stocktaker Instructions Protocol --}}
        <div class="instructions-box">
            <strong><i class="mdi mdi-clipboard-text-clock mr-1"></i> Stock Count &amp; Verification Protocol:</strong>
            1. Count all physical units currently located on racks, shelves, storage bins, and lockers.
            2. Follow the stated <strong>Packaging Levels</strong> (e.g. Cartons &rarr; Packs &rarr; Units). Count sealed packs and loose pieces separately.
            3. Enter the verified total base quantity in <strong>Physical Verification Count</strong> and calculate <strong>Variance (+/-)</strong> (Shelf Count minus EMR Qty).
            4. Record batch differences, broken seals, or expired stock in <strong>Audit Status &amp; Notes</strong>.
            5. Ensure both the storekeeper and independent auditor sign and stamp upon completion.
        </div>

        {{-- Verification Table --}}
        <table class="count-table">
            <thead>
                <tr>
                    <th style="width: 3%;">S/N</th>
                    <th style="width: 17%; text-align: left;">Product / Item Description</th>
                    <th style="width: 12%; text-align: left;">Packaging Levels &amp; Hierarchy</th>
                    <th style="width: 22%; text-align: left;">Active Batches, Expiry &amp; Custody</th>
                    <th style="width: 10%;">EMR Recorded Stock</th>
                    <th style="width: 16%;">Physical Verification Count</th>
                    <th style="width: 7%;">Variance (+/-)</th>
                    <th style="width: 13%; text-align: left;">Audit Status &amp; Notes</th>
                </tr>
            </thead>
            <tbody>
                @forelse($items as $index => $item)
                @php
                    $p = $item->product;
                @endphp
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td class="text-left">
                        <span class="prod-code">{{ $p->product_code ?? 'NO-CODE' }}</span>
                        <span class="prod-name">{{ $p->product_name ?? 'Unknown Product' }}</span>
                        <span class="prod-cat">{{ $p->category->category_name ?? 'Uncategorized' }}</span>
                    </td>
                    <td class="text-left">
                        <span class="pkg-base-tag">Base: {{ $item->base_unit ?? 'Unit' }}</span>
                        @if($item->packagings && $item->packagings->count() > 0)
                            @foreach($item->packagings as $pkg)
                                <div class="pkg-level-line">
                                    <strong>{{ $pkg->name }}</strong> (L{{ $pkg->level }}): = {{ number_format($pkg->base_unit_qty, $pkg->base_unit_qty == intval($pkg->base_unit_qty) ? 0 : 2) }} {{ $item->base_unit ?? 'units' }}
                                    @if($pkg->is_default_purchase)<span class="pkg-subtag">Purch</span>@endif
                                </div>
                            @endforeach
                        @elseif(!empty($p->howmany_to) && $p->howmany_to > 1)
                            <div class="pkg-level-line">Pack of {{ number_format($p->howmany_to) }} {{ $item->base_unit ?? 'units' }}</div>
                        @else
                            <div class="text-muted" style="font-size: 8.5px; font-style: italic;">Standard Unit (1 {{ $item->base_unit ?? 'Unit' }})</div>
                        @endif
                    </td>
                    <td class="text-left">
                        @if($item->batches && $item->batches->count() > 0)
                            @foreach($item->batches as $b)
                                @php
                                    $expDate = $b->expiry_date ? \Carbon\Carbon::parse($b->expiry_date) : null;
                                    $isExpired = $expDate && $expDate->isPast();
                                    $isExpSoon = $expDate && !$isExpired && $expDate->diffInDays(now()) <= 90;
                                    $badgeClass = 'badge-valid';
                                    $badgeText = $expDate ? $expDate->format('d-M-Y') : 'No Expiry';
                                    if ($isExpired) {
                                        $badgeClass = 'badge-expired';
                                        $badgeText .= ' (Expired)';
                                    } elseif ($isExpSoon) {
                                        $badgeClass = 'badge-soon';
                                        $badgeText .= ' (Exp Soon)';
                                    } elseif (!$expDate) {
                                        $badgeClass = 'badge-na';
                                    }
                                @endphp
                                <div class="batch-detail-card">
                                    <div class="batch-header-row">
                                        <span class="batch-code"><i class="mdi mdi-barcode mr-1"></i>{{ $b->batch_number }}</span>
                                        <span class="batch-exp-badge {{ $badgeClass }}">{{ $badgeText }}</span>
                                    </div>
                                    <div class="batch-qty-row">
                                        <span class="batch-qty-val">{{ number_format($b->current_qty) }} {{ $item->base_unit ?? 'units' }}</span>
                                        @if(!empty($b->pack_breakdown))
                                            <span class="batch-pack-equiv"><i class="mdi mdi-package-variant-closed mr-1"></i>{{ $b->pack_breakdown }}</span>
                                        @endif
                                    </div>
                                    @if($b->collected_by_name || $b->approved_by_name || $b->fulfilled_by_name || $b->source_origin)
                                    <div class="batch-custody-row">
                                        @if($b->collected_by_name)
                                        <div class="custody-item">
                                            <span class="custody-lbl">Collected:</span>
                                            <span class="custody-val">
                                                {{ $b->collected_by_name }}
                                                @if($b->collected_at)<span class="custody-time">({{ $b->collected_at }})</span>@endif
                                            </span>
                                        </div>
                                        @endif
                                        @if($b->approved_by_name)
                                        <div class="custody-item">
                                            <span class="custody-lbl">Approved:</span>
                                            <span class="custody-val">
                                                {{ $b->approved_by_name }}
                                                @if($b->approved_at)<span class="custody-time">({{ $b->approved_at }})</span>@endif
                                            </span>
                                        </div>
                                        @endif
                                        @if($b->fulfilled_by_name)
                                        <div class="custody-item">
                                            <span class="custody-lbl">Fulfilled:</span>
                                            <span class="custody-val">
                                                {{ $b->fulfilled_by_name }}
                                                @if($b->fulfilled_at)<span class="custody-time">({{ $b->fulfilled_at }})</span>@endif
                                            </span>
                                        </div>
                                        @endif
                                        @if($b->source_origin)
                                        <div class="custody-item">
                                            <span class="custody-lbl">Source:</span>
                                            <span class="custody-val">
                                                {{ $b->source_origin }}
                                                @if($b->source_date)<span class="custody-time">({{ $b->source_date }})</span>@endif
                                            </span>
                                        </div>
                                        @endif
                                    </div>
                                    @endif
                                </div>
                            @endforeach
                        @else
                            <span class="text-muted" style="font-size: 9px; font-style: italic;">No active batches</span>
                        @endif
                    </td>
                    <td class="text-center">
                        <div style="font-size: 11.5px; font-weight: 700; color: #0f172a;">
                            {{ number_format($item->current_quantity) }} <span style="font-size: 9px; font-weight: 600; color: #64748b;">{{ $item->base_unit ?? 'units' }}</span>
                        </div>
                        @if(!empty($item->bulk_breakdown))
                            <span class="emr-bulk-equiv">{{ $item->bulk_breakdown }}</span>
                        @endif
                    </td>
                    <td>
                        <div class="phys-count-box">
                            <div class="phys-row">
                                <span class="phys-lbl">Packs:</span>
                                <span class="blank-writein"></span>
                            </div>
                            <div class="phys-row">
                                <span class="phys-lbl">Loose:</span>
                                <span class="blank-writein"></span>
                            </div>
                            <div class="phys-total-row">
                                <span class="phys-lbl-bold">Total:</span>
                                <span class="blank-writein-total"></span>
                            </div>
                        </div>
                    </td>
                    <td class="blank-var-box">
                        <span class="blank-writein-var"></span>
                    </td>
                    <td>
                        <div class="audit-check-box">
                            <div class="chk-row">
                                <span>[ ] Match</span>
                                <span>[ ] Var</span>
                            </div>
                            <div class="chk-row">
                                <span>[ ] Dmg</span>
                                <span>[ ] Exp</span>
                            </div>
                            <div style="border-bottom: 1px dashed #cbd5e1; height: 10px; margin-top: 3px;"></div>
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="8" class="text-center" style="padding: 24px; color: #64748b;">
                        No stock items found matching the specified filter criteria.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>

        {{-- Formal 4-Card Certification Sign-Off Block --}}
        <div class="signoff-section">
            <div class="signoff-title">
                <i class="mdi mdi-certificate-outline"></i> Physical Inventory Verification Certification &amp; Sign-Off
            </div>
            <div class="signoff-grid">

                <div class="sign-card">
                    <div class="sign-role">Conducted By (Primary Stocktaker)</div>
                    <div class="sign-field">Name: <span class="sign-line"></span></div>
                    <div class="sign-field">Staff ID: <span class="sign-line"></span></div>
                    <div class="sign-field">Signature: <span class="sign-line"></span></div>
                    <div class="sign-field">Date / Time: <span class="sign-line"></span></div>
                </div>

                <div class="sign-card">
                    <div class="sign-role">Witnessed / Verified By</div>
                    <div class="sign-field">Name: <span class="sign-line"></span></div>
                    <div class="sign-field">Staff ID: <span class="sign-line"></span></div>
                    <div class="sign-field">Signature: <span class="sign-line"></span></div>
                    <div class="sign-field">Date / Time: <span class="sign-line"></span></div>
                </div>

                <div class="sign-card">
                    <div class="sign-role">Store Custodian / Department Head</div>
                    <div class="sign-field">Name: <span class="sign-line"></span></div>
                    <div class="sign-field">Signature: <span class="sign-line"></span></div>
                    <div class="sign-field">Date: <span class="sign-line"></span></div>
                    <div class="stamp-box">Official Store Stamp</div>
                </div>

                <div class="sign-card">
                    <div class="sign-role">Internal Audit Department Approval</div>
                    <div class="sign-field">Auditor Name: <span class="sign-line"></span></div>
                    <div class="sign-field">Signature: <span class="sign-line"></span></div>
                    <div class="sign-field">Date: <span class="sign-line"></span></div>
                    <div class="stamp-box">Internal Audit Stamp</div>
                </div>

            </div>
        </div>

        {{-- Document Footer --}}
        <div class="doc-footer">
            {{ $siteName }} &bull; Inventory Management Module &bull; Physical Stock Audit Instrument &bull; Printed On: {{ date('d M Y, h:i:s A') }}
        </div>

    </div>

</body>
</html>
