<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EPI Community Outreach Immunization Summary Report ({{ $from }} to {{ $to }})</title>
    <style>
        :root {
            --brand: {{ appsettings('hos_color', '#011b33') }};
            --ink: #0f172a;
            --muted: #64748b;
            --border: #cbd5e1;
            --bg: #ffffff;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
            font-size: 8.5pt;
            color: var(--ink);
            background: #fff;
            padding: 18px;
        }
        .header-box {
            border-bottom: 2px solid var(--brand);
            padding-bottom: 10px;
            margin-bottom: 12px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .header-title h2 {
            font-size: 13pt;
            font-weight: 800;
            color: var(--brand);
            text-transform: uppercase;
        }
        .header-title h4 {
            font-size: 9.5pt;
            font-weight: 600;
            color: #334155;
            margin-top: 2px;
        }
        .header-meta {
            font-size: 8pt;
            color: #475569;
            margin-top: 4px;
        }
        .header-badge {
            text-align: right;
            font-size: 8pt;
        }
        .kpi-row {
            display: flex;
            gap: 10px;
            margin-bottom: 14px;
        }
        .kpi-box {
            flex: 1;
            border: 1px solid var(--border);
            border-radius: 4px;
            padding: 6px 8px;
            background: #f8fafc;
            text-align: center;
        }
        .kpi-title {
            font-size: 7.5pt;
            color: var(--muted);
            text-transform: uppercase;
            font-weight: 700;
        }
        .kpi-value {
            font-size: 13pt;
            font-weight: 800;
            color: var(--brand);
            margin-top: 2px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 8pt;
            margin-top: 8px;
        }
        th, td {
            border: 1px solid var(--border);
            padding: 5px 6px;
            text-align: left;
        }
        th {
            background: #f1f5f9;
            font-weight: 700;
            color: #1e293b;
        }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .badge {
            display: inline-block;
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 7.5pt;
            font-weight: 600;
            background: #e2e8f0;
        }
        .footer-signatures {
            margin-top: 25px;
            display: flex;
            justify-content: space-between;
            page-break-inside: avoid;
        }
        .signature-line {
            width: 200px;
            border-top: 1px dashed #64748b;
            padding-top: 5px;
            font-size: 8pt;
            text-align: center;
        }
        @media print {
            .no-print { display: none !important; }
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 12px; text-align: right;">
        <button onclick="window.print()" style="padding: 6px 14px; background: var(--brand); color: #fff; border: none; border-radius: 4px; cursor: pointer; font-weight: 600;">
            Print / Save PDF
        </button>
    </div>

    <div class="header-box">
        <div class="header-title">
            <h2>{{ appsettings('site_name', 'COREHEALTH HOSPITAL') }}</h2>
            <h4>COMMUNITY OUTREACH IMMUNIZATION SUMMARY (WHO EPI / NHMIS FORM 001)</h4>
            <div class="header-meta">
                Period: <strong>{{ \Carbon\Carbon::parse($from)->format('d M Y') }}</strong> to <strong>{{ \Carbon\Carbon::parse($to)->format('d M Y') }}</strong>
                @if($location) | Settlement / Site: <strong>{{ $location }}</strong> @endif
            </div>
        </div>
        <div class="header-badge">
            <div>Printed: <strong>{{ \Carbon\Carbon::now()->format('d M Y, h:i A') }}</strong></div>
            <div>Generated by: <strong>{{ auth()->user()?->name ?? 'System' }}</strong></div>
        </div>
    </div>

    @php
        $totalDoses = $records->sum('headcount');
        $totalWasted = $records->sum('doses_wasted');
        $infants = $records->filter(fn($r) => in_array($r->age_group, ['<1y', '0-11m']) || $r->target_group === 'infants')->sum('headcount');
        $children = $records->filter(fn($r) => in_array($r->age_group, ['12-59m', 'ge_1y', '5-9y']) || in_array($r->target_group, ['children_1_4', 'school_age_5_9']))->sum('headcount');
        $hpv = $records->filter(fn($r) => $r->age_group === '9-14y' || $r->target_group === 'adolescent_girls' || str_contains(strtolower($r->vaccine_name), 'hpv'))->sum('headcount');
        $pregnant = $records->filter(fn($r) => $r->target_group === 'pregnant_women' || str_contains(strtolower($r->notes ?? ''), 'pregnant'))->sum('headcount');
        $wra = $records->filter(fn($r) => $r->target_group === 'non_pregnant_women' || str_contains(strtolower($r->notes ?? ''), 'non-pregnant'))->sum('headcount');
    @endphp

    <div class="kpi-row">
        <div class="kpi-box">
            <div class="kpi-title">Total Records</div>
            <div class="kpi-value">{{ $records->count() }}</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-title">Doses Administered</div>
            <div class="kpi-value">{{ $totalDoses }}</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-title">Doses Wasted</div>
            <div class="kpi-value" style="color: #dc2626;">{{ $totalWasted }}</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-title">Infants &lt; 1y</div>
            <div class="kpi-value">{{ $infants }}</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-title">Children &ge; 1y</div>
            <div class="kpi-value">{{ $children }}</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-title">HPV Girls (9–14y)</div>
            <div class="kpi-value">{{ $hpv }}</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-title">Maternal Td (PW)</div>
            <div class="kpi-value">{{ $pregnant }}</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-title">Non-Pregnant WRA</div>
            <div class="kpi-value">{{ $wra }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 4%;">#</th>
                <th style="width: 9%;">Date</th>
                <th style="width: 12%;">Session ID</th>
                <th style="width: 15%;">Settlement / Site</th>
                <th style="width: 13%;">Stock Source</th>
                <th style="width: 14%;">Antigen / Dose</th>
                <th style="width: 13%;">Demographic</th>
                <th style="width: 5%;">Sex</th>
                <th style="width: 5%; text-align: center;">Tally</th>
                <th style="width: 10%;">Vaccinator</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $idx => $r)
                <tr>
                    <td>{{ $idx + 1 }}</td>
                    <td>{{ $r->administered_at ? \Carbon\Carbon::parse($r->administered_at)->format('d/m/Y') : '-' }}</td>
                    <td><strong>{{ $r->outreach_session_id ?: 'LEGACY' }}</strong></td>
                    <td>{{ $r->location_settlement ?: 'Community Site' }}</td>
                    <td>
                        @php
                            $sourceLabels = [
                                'govt_epi' => 'Govt Free EPI',
                                'hospital_store' => 'Hospital Store' . ($r->dispensedFromStore ? ' (' . $r->dispensedFromStore->store_name . ')' : ''),
                                'donor_partner' => 'Partner/Donor',
                                'outbreak_reserve' => 'Outbreak Reserve',
                            ];
                        @endphp
                        <span class="badge" style="background: #e2e8f0; color: #1e293b;">
                            {{ $sourceLabels[$r->stock_source] ?? 'Govt EPI' }}
                        </span>
                        @if($r->vvm_stage)
                            <br><small style="color: #64748b;">VVM: {{ $r->vvm_stage }}</small>
                        @endif
                    </td>
                    <td><strong>{{ $r->vaccine_name }}</strong> ({{ $r->dose ?: 'Dose 1' }})</td>
                    <td>
                        <span class="badge">{{ $r->target_group ?: ($r->age_group ?: 'All Ages') }}</span>
                    </td>
                    <td>{{ $r->gender ?: 'All' }}</td>
                    <td class="text-center" style="font-weight: 700; font-size: 9pt;">{{ $r->headcount }}</td>
                    <td>{{ $r->administeredBy ? userfullname($r->administeredBy->id) : 'EPI Team' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="10" class="text-center" style="padding: 20px; color: #64748b;">
                        No community outreach immunization tallies found for the selected criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
        @if($records->count() > 0)
        <tfoot>
            <tr style="background: #f1f5f9; font-weight: 700;">
                <td colspan="8" class="text-right">TOTAL OUTREACH DOSES ADMINISTERED:</td>
                <td class="text-center" style="font-size: 10pt; color: var(--brand);">{{ $totalDoses }}</td>
                <td></td>
            </tr>
        </tfoot>
        @endif
    </table>

    <div class="footer-signatures">
        <div class="signature-line">
            EPI Field Team Leader
        </div>
        <div class="signature-line">
            LGA Immunization Officer (LIO)
        </div>
        <div class="signature-line">
            Hospital Head of Clinical Services
        </div>
    </div>
</body>
</html>
