<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Trial Balance</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .header h2 {
            margin: 5px 0;
            font-size: 16px;
            font-weight: normal;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
            border-bottom: 2px solid #333;
        }
        .text-right {
            text-align: right;
        }
        .total-row {
            font-weight: bold;
            background-color: #f0f0f0;
            border-top: 2px solid #333;
        }
        .balance-check {
            margin-top: 20px;
            padding: 10px;
            text-align: center;
        }
        .balanced {
            background-color: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }
        .unbalanced {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            width: 100%;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .footer .left {
            float: left;
        }
        .footer .right {
            float: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name', 'CoreHealth Hospital') }}</h1>
        <h2>Trial Balance</h2>
        <p>As of {{ $asOfDate->format('F d, Y') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">Account Code</th>
                <th style="width: 45%;">Account Name</th>
                <th style="width: 20%;" class="text-right">Debit</th>
                <th style="width: 20%;" class="text-right">Credit</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalDebit = 0;
                $totalCredit = 0;
            @endphp
            @foreach($accounts as $account)
                <tr>
                    <td>{{ $account['code'] }}</td>
                    <td>{{ $account['name'] }}</td>
                    <td class="text-right">{{ $account['debit'] > 0 ? number_format($account['debit'], 2) : '' }}</td>
                    <td class="text-right">{{ $account['credit'] > 0 ? number_format($account['credit'], 2) : '' }}</td>
                </tr>
                @php
                    $totalDebit += $account['debit'];
                    $totalCredit += $account['credit'];
                @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="2">TOTALS</td>
                <td class="text-right">{{ number_format($totalDebit, 2) }}</td>
                <td class="text-right">{{ number_format($totalCredit, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    @php $isBalanced = abs($totalDebit - $totalCredit) < 0.01; @endphp
    <div class="balance-check {{ $isBalanced ? 'balanced' : 'unbalanced' }}">
        @if($isBalanced)
            <strong>✓ Trial Balance is BALANCED</strong>
        @else
            <strong>✗ Trial Balance is OUT OF BALANCE</strong><br>
            Difference: {{ number_format(abs($totalDebit - $totalCredit), 2) }}
        @endif
    </div>

    <div class="footer">
        <span class="left">Generated on: {{ now()->format('F d, Y H:i:s') }}</span>
        <span class="right">Generated by: {{ auth()->user()->name ?? 'System' }}</span>
    </div>
</body>
</html>
