{{-- Invoice A4 Template --}}
<!DOCTYPE html>
<html>
<head>
    <title>Invoice (A4)</title>
    <style>
        :root {
            --brand: {{ $site->hos_color ?? '#0a6cf2' }};
            --ink: #1d1d1f;
            --muted: #5f6368;
            --border: #d7d9dc;
            --bg: #f7f9fb;
            --warning: #f59e0b;
        }
        * { box-sizing: border-box; }
        .invoice-a4 { margin: 0; padding: 24px; font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px; color: var(--ink); background: var(--bg); }
        .invoice-a4 .sheet { background: #fff; border: 1px solid var(--border); border-radius: 8px; padding: 24px; box-shadow: 0 8px 24px rgba(0,0,0,0.04); max-width: 900px; width: 100%; margin: 0 auto; }
        .invoice-a4 .brand-bar { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid var(--brand); padding-bottom: 12px; margin-bottom: 16px; }
        .invoice-a4 .brand-left { display: flex; align-items: center; gap: 12px; }
        .invoice-a4 .brand-left img { width: 72px; height: auto; }
        .invoice-a4 .brand-name { font-size: 20px; font-weight: 700; color: var(--brand); letter-spacing: 0.5px; }
        .invoice-a4 .brand-meta { font-size: 12px; color: var(--muted); line-height: 1.4; }
        .invoice-a4 .doc-title { text-align: right; font-size: 24px; font-weight: 700; letter-spacing: 1px; color: var(--warning); }
        .invoice-a4 .doc-title small { display: block; font-size: 12px; color: var(--muted); font-weight: 500; }
        .invoice-a4 .proforma-badge { display: inline-block; background: rgba(245,158,11,0.15); color: var(--warning); padding: 4px 12px; border-radius: 4px; font-size: 11px; font-weight: 700; letter-spacing: 1px; margin-top: 4px; }
        .invoice-a4 .details { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 8px 16px; margin-bottom: 16px; }
        .invoice-a4 .details div { font-size: 13px; color: var(--ink); }
        .invoice-a4 .badge { display: inline-block; background: rgba(10,108,242,0.08); color: var(--brand); padding: 3px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; letter-spacing: 0.2px; }
        .invoice-a4 .badge-hmo { background: rgba(16,185,129,0.1); color: #059669; }
        .invoice-a4 table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        .invoice-a4 th, .invoice-a4 td { border: 1px solid var(--border); padding: 8px 10px; font-size: 12px; }
        .invoice-a4 thead th { background: rgba(245,158,11,0.08); color: var(--ink); font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; }
        .invoice-a4 tbody tr:nth-child(even) { background: #fff; }
        .invoice-a4 tbody tr:nth-child(odd) { background: #fbfcfd; }
        .invoice-a4 tfoot td { font-weight: 700; font-size: 13px; }
        .invoice-a4 .notes { margin-top: 12px; font-size: 12px; color: var(--warning); border-left: 3px solid var(--warning); padding-left: 10px; background: rgba(245,158,11,0.05); padding: 8px 10px; border-radius: 4px; }
        .invoice-a4 .footer { margin-top: 18px; text-align: right; font-size: 12px; color: var(--muted); }
        .invoice-a4 .total-row { background: rgba(245,158,11,0.1) !important; }
        .invoice-a4 .hmo-row { background: rgba(16,185,129,0.05) !important; color: #059669; }
        @media print {
            @page { size: A4; margin: 10mm; }
            .invoice-a4 { background: #fff; padding: 0; }
            .invoice-a4 .sheet { box-shadow: none; border: none; margin: 0; width: 100%; max-width: none; }
        }
    </style>
</head>
<body>
    <div class="invoice-a4">
    <div class="sheet">
        <div class="brand-bar">
            <div class="brand-left">
                <img src="data:image/jpeg;base64,{{ $site->logo }}" alt="Logo">
                <div>
                    <div class="brand-name">{{ $site->site_name }}</div>
                    <div class="brand-meta">{{ $site->contact_address }}<br>Phone: {{ $site->contact_phones }} | Email: {{ $site->contact_emails }}</div>
                </div>
            </div>
            <div class="doc-title">
                INVOICE
                <small>{{ $invoiceNo }}</small>
                <div class="proforma-badge">PROFORMA / UNPAID</div>
            </div>
        </div>

        <div class="details">
            <div><span class="badge">Patient</span><br><strong>{{ $patientName }}</strong></div>
            <div><span class="badge">File No.</span><br>{{ $patientFileNo ?? 'N/A' }}</div>
            <div><span class="badge">Date</span><br>{{ $date }}</div>
            @if($hmoName)
            <div><span class="badge badge-hmo">HMO</span><br>{{ $hmoName }} {{ $hmoNo ? "($hmoNo)" : '' }}</div>
            @endif
            <div><span class="badge">Generated By</span><br>{{ $currentUserName }}</div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Unit Price</th>
                    <th>Qty</th>
                    <th>Disc %</th>
                    <th>HMO (₦)</th>
                    <th>Amount (₦)</th>
                </tr>
            </thead>
            <tbody>
            @foreach($invoiceDetails as $i => $row)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td style="white-space: nowrap;">{{ $row['date'] }}</td>
                    <td>{{ $row['name'] }} <small style="color: var(--muted);">({{ $row['type'] }})</small></td>
                    <td style="text-align: right;">{{ number_format($row['price'], 2) }}</td>
                    <td style="text-align: center;">{{ $row['qty'] }}</td>
                    <td style="text-align: center;">{{ $row['discount_percent'] }}%</td>
                    <td style="text-align: right; color: #059669;">{{ $row['hmo_coverage'] > 0 ? number_format($row['hmo_coverage'], 2) : '-' }}</td>
                    <td style="text-align: right;">{{ number_format($row['amount'], 2) }}</td>
                </tr>
            @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7" style="text-align: right;">Subtotal</td>
                    <td style="text-align: right;">₦{{ number_format($totalAmount + $totalDiscount, 2) }}</td>
                </tr>
                @if($totalDiscount > 0)
                <tr>
                    <td colspan="7" style="text-align: right;">Total Discount</td>
                    <td style="text-align: right; color: #dc2626;">-₦{{ number_format($totalDiscount, 2) }}</td>
                </tr>
                @endif
                <tr>
                    <td colspan="7" style="text-align: right;">Total Amount</td>
                    <td style="text-align: right;">₦{{ number_format($totalAmount, 2) }}</td>
                </tr>
                @if($totalHmoCoverage > 0)
                <tr class="hmo-row">
                    <td colspan="7" style="text-align: right;">HMO Coverage</td>
                    <td style="text-align: right;">-₦{{ number_format($totalHmoCoverage, 2) }}</td>
                </tr>
                @endif
                <tr class="total-row">
                    <td colspan="7" style="text-align: right; font-size: 14px;"><strong>PATIENT PAYABLE</strong></td>
                    <td style="text-align: right; font-size: 16px;"><strong>₦{{ number_format($patientPayable, 2) }}</strong></td>
                </tr>
            </tfoot>
        </table>

        <div style="margin-top:12px; font-size:12px; color: var(--ink);"><strong>Amount in Words:</strong> {{ $amountInWords ?? '' }}</div>

        @if(!empty($notes))
        <div class="notes"><strong>⚠ Note:</strong> {{ $notes }}</div>
        @endif

        <div class="footer">
            Generated: {{ now()->format('Y-m-d H:i:s') }} | This invoice is valid for 7 days from date of issue.
        </div>
    </div>
    </div>
</body>
</html>
