{{-- filepath: c:\Users\MrApollos\Documents\work\corehealth_v2\resources\views\admin\Accounts\receipt_thermal.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <title>Receipt (Thermal)</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; width: 210px; }
        .receipt-header { text-align: center; margin-bottom: 6px; }
        .receipt-header img { width: 60px; }
        .receipt-table { width: 100%; border-collapse: collapse; margin-bottom: 6px; }
        .receipt-table th, .receipt-table td { border: 1px solid #888; padding: 2px 4px; font-size: 10px; }
        .receipt-notes { margin-top: 6px; font-size: 10px; }
        .receipt-btns { margin-top: 10px; text-align: center; }
        .receipt-footer { margin-top: 15px; text-align: right; font-size: 10px; }
        @media print { .receipt-btns { display: none; } }
    </style>
</head>
<body>
    <div class="receipt-header">
        <img src="data:image/jpeg;base64,{{ $site->logo }}" alt="Logo"/><br>
        <strong>{{ $site->site_name }}</strong><br>
        {{ $site->contact_address }}<br>
        Phone: {{ $site->contact_phones }}
        <hr>
        <div style="font-size: 13px; font-weight: bold;">RECEIPT</div>
    </div>
    <div>
        <b>Patient:</b> {{ $patientName }}<br>
        <b>Date:</b> {{ $date }}<br>
        <b>Ref:</b> {{ $ref }}<br>
        <b>Served By:</b> {{ $currentUserName }}<br>
    </div>
    <table class="receipt-table">
        <thead>
            <tr>
                <th>Type</th>
                <th>Name</th>
                <th>Unit</th>
                <th>Qty</th>
                <th>Disc(%)</th>
                <th>Disc(₦)</th>
                <th>Paid(₦)</th>
            </tr>
        </thead>
        <tbody>
        @foreach($receiptDetails as $row)
            <tr>
                <td>{{ $row['type'] }}</td>
                <td>{{ $row['name'] }}</td>
                <td>{{ number_format($row['price'], 2) }}</td>
                <td>{{ $row['qty'] }}</td>
                <td>{{ $row['discount_percent'] }}</td>
                <td>{{ number_format($row['discount_amount'], 2) }}</td>
                <td>{{ number_format($row['amount_paid'], 2) }}</td>
            </tr>
        @endforeach
            <tr>
                <td colspan="5" align="right"><strong>Total Discount:</strong></td>
                <td colspan="2"><strong>{{ number_format($totalDiscount, 2) }}</strong></td>
            </tr>
            <tr>
                <td colspan="5" align="right"><strong>Grand Total Paid:</strong></td>
                <td colspan="2"><strong>{{ number_format($totalPaid, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>
    <div class="receipt-notes">
        {!! $notes !!}
    </div>
    <div class="receipt-footer">
        <em>Generated by: {{ $currentUserName }}</em>
    </div>
    <div class="receipt-btns">
        <button onclick="window.print()">Print</button>
        <button onclick="window.location.href='{{ url('product-or-service-request') }}'">Close</button>
    </div>
</body>
</html>
